version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: conduit_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-conduit_local}
      POSTGRES_USER: ${DB_USER:-conduit}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-conduit}
    ports:
      - "5432:5432"
    volumes:
      - ./demo-app/.postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-conduit} -d ${DB_NAME:-conduit_local}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  demo-backend:
    image: node:18
    container_name: conduit_backend
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./demo-app/src:/app
      - ./demo-app/src/backend/.env:/app/backend/.env:ro
    environment:
      NODE_ENV: development
    command: >-
      bash -lc "npm install && npm run sqlz -- db:migrate && npm run dev -w backend"
    ports:
      - "3001:3001"

  demo-frontend:
    image: node:18
    container_name: conduit_frontend
    working_dir: /app
    depends_on:
      demo-backend:
        condition: service_started
    volumes:
      - ./demo-app/src:/app
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://conduit_backend:3001
    command: >-
      bash -lc "npm install && npm run dev -w frontend -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
