description: Offline NLQ agent scoring
prompts: prompt.txt
providers:
  - id: ollama:gemma3:4b
    label: gemma3-4b
    config:
      baseUrl: "{{env.OLLAMA_BASE_URL}}"
      options:
        temperature: 0
  - id: ollama:deepseek-r1:8b
    label: deepseek-r1-8b
    config:
      baseUrl: "{{env.OLLAMA_BASE_URL}}"
      options:
        temperature: 0

defaultTest:
  options:
    maxOutputTokens: 256
  assertions:
    - type: is-json
      value:
        required: [rank, passable, reason]
        properties:
          rank:
            type: number
          passable:
            type: boolean
          reason:
            type: string
    - type: javascript
      value: |
        const data = JSON.parse(output);
        if (!Number.isInteger(data.rank) || data.rank < 1 || data.rank > 5) {
          throw new Error(`rank must be an integer between 1 and 5: ${data.rank}`);
        }
        if (typeof data.passable !== 'boolean') {
          throw new Error('passable must be boolean');
        }
        if (typeof data.reason !== 'string' || data.reason.length === 0 || data.reason.length > 80) {
          throw new Error('reason must be a non-empty string <= 80 characters');
        }

tests:
  - description: Simple timeframe question
    vars:
      table_defs: |
        CREATE TABLE sessions (
          id SERIAL PRIMARY KEY,
          created TIMESTAMP NOT NULL,
          duration_minutes INTEGER NOT NULL,
          status TEXT NOT NULL
        );
      question: "How many sessions were completed last week, grouped by status?"
      rules: |
        - Mention the table names explicitly.
        - Include a timeframe filter.
        - Prefer aggregate questions over row-by-row retrieval.
  - description: Missing timeframe should lower score
    vars:
      table_defs: |
        CREATE TABLE invoices (
          id SERIAL PRIMARY KEY,
          total NUMERIC(10,2) NOT NULL,
          issued TIMESTAMP NOT NULL,
          customer_id INTEGER NOT NULL
        );
      question: "List invoice totals for every customer"
      rules: |
        - Include a timeframe filter.
        - Limit the result to at most 20 rows.
        - Mention the invoices table explicitly by name.
