name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Node dependencies
        run: npm install

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Start demo stack
        run: docker compose up -d postgres demo-backend demo-frontend

      - name: Wait for services
        run: python scripts/health_check.py --env-file config/demo.env

      - name: Seed demo data
        run: python scripts/seed_demo_data.py --env-file config/demo.env

      - name: Run tests
        run: python -m pytest

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: ignore

      - name: Tear down stack
        if: always()
        run: docker compose down
